### PR TITLE
Make running code in the browser possible again.

### PR DESCRIPTION
**Pull request by egasimus**
Hello @Gozala :-)
I noticed that `engine/browser.wisp` looks for the non-existent `compile*` function, preventing any code to be compiled in a browser environment. I've patched it with the code from `engines/node.wisp`, and it seems to work.
Thanks for providing a JVM-free alternative to ClojureScript! :-)

### CODE REVIEW

**Comment by egasimus** [comment]
Whew, that took a few tries to get right.

**Comment by Gozala** [comment]
@egasimus I'm so sorry I have not got to it so long. I'll try to deal with all pending pulls this week.

**Comment by egasimus** [comment]
No worries, I still haven't gotten around to the macro import stuff that we talked about either -- though I've got a big Wisp project in the works and will probably look into that as soon as inevitable :)

**Comment by impinball** [comment]
@Gozala I guess you've been busy?

**Comment by egasimus** [comment]
Closing this PR -- will redo my patches in separate branches on top of latest upstream.

**Pull request closed without merging**
