### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rcarmo**
Minify, in particular, has a security issue in one of its dependencies. Am going to go through the others to see if the build passes.

### CODE REVIEW

**Comment by chr15m** [comment]
@rcarmo looks good, do you want to squash those commits to neaten this up and I'll merge. Thanks so much!

**Comment by rcarmo** [comment]
I want to try to figure out escodegen first. It “works” but fails the tests, probably because it generates code differently.

**Comment by chr15m** [comment]
@rcarmo :+1: would be good to have that working!

**Comment by LeXofLeviafan** [comment]
I believe this issue [had been fixed](https://github.com/Gozala/wisp/commit/61cf5e5e0e4ac6b469af40908eda0e15425c7ffa).
(Or at least Github stopped screaming warnings at me since after I updated Wisp dependency to latest version in a project of mine.)

**Comment by chr15m** [comment]
@LeXofLeviafan thanks, closing.

**Pull request closed without merging**
