### PR TITLE
Additional fixes after browser testing

### PR DESCRIPTION
**Pull request by LeXofLeviafan**
I've been making sort of a makeshift live-documentation on Wisp (mostly as a form of exercise), and stumbled upon a few bugs in the new version while I was at it. (If you're curious, you can check it out [here](https://lexofleviafan.noip.me/demo/wisp).)
One of these bugs passed all tests because testing isn't made on the same transpilation output that goes into release build… That probably is not a good thing :-D

### CODE REVIEW

**Comment by chr15m** [comment]
Thanks!

**Comment by chr15m** [comment]
@LeXofLeviafan by the way I could not get your demo page to load. From what I can tell it seems like it may be along the same lines as @Gozala's original Wisp documentation. Would love to see it in action.

**Comment by LeXofLeviafan** [comment]
>I could not get your demo page to load

Huh. Weird. The online availability tests seem to work fine (except for a few servers but they don't receive any data at all), and WebPageTest even shows correctly rendered screenshots.
Are you perhaps using a browser or proxy that refuses to download script tags with MIME `application/wisp`? That seems to be the most likely issue…

[Here's](https://685bb300-eeb4-447a-be01-c1c81883378d.htmlpasta.com) a rolled-up version (the only external file is `wisp.min.js` from a CDN); perhaps it would work for you.

**Comment by chr15m** [comment]
@LeXofLeviafan Wow, that's amazing!

**Pull request merged**
